server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:memberDB;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true

  jackson:
    serialization:
      fail-on-empty-beans: false
  h2:
    console:
      enabled: true
      path: /h2-console


jwt:
  header: Authorization
  #kwonheewoon user api project
  secret: a3dvbmhlZXdvb24gdXNlciBhcGkgcHJvamVjdCBzcmMubWFpbi5qYXZhLm1haW4ucmVmdW5kc2FwaSBwYWNrYWdl
  token-validity-in-seconds: 86400

seed-util:
  user-key: testCrypt2020!@#
  iv: 1234567890123456